# -*- coding: utf-8 -*-
"""Image segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3lfhRaZk4DAGYIfzM3JPD_GGzSKREzg
"""

# Step 1: Install the necessary libraries
!pip install transformers
!pip install torch torchvision
!pip install pillow

# Step 2: Import the necessary modules
from transformers import pipeline
from PIL import Image
import requests
import matplotlib.pyplot as plt
import numpy as np

# Step 3: Create an image segmentation pipeline
image_segmenter = pipeline(task="image-segmentation")

# Step 4: Define the image you want to segment
image_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/2018_IMG_8253_Helsinki%2C_Finland_%2840249531641%29_%28cropped%29.jpg/800px-2018_IMG_8253_Helsinki%2C_Finland_%2840249531641%29_%28cropped%29.jpg"
image = Image.open(requests.get(image_url, stream=True).raw)

# Step 5: Perform image segmentation
results = image_segmenter(image)

# Step 6: Display the segmentation results
plt.figure(figsize=(10, 10))
plt.imshow(image)
plt.axis('off')

# Overlay the segmentation masks with different colors
for result in results:
    mask = np.array(result['mask'])
    plt.imshow(mask, alpha=0.5, cmap='jet')

plt.show()

