# -*- coding: utf-8 -*-
"""Visual question answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGYfrYXxpeLlMQzJM-0b0r_TI0dv4TGv
"""

# Step 1: Install the necessary libraries
!pip install transformers
!pip install torch torchvision
!pip install pillow

# Step 2: Import the necessary modules
from PIL import Image
from transformers import pipeline

# Step 3: Create a Visual Question Answering pipeline
vqa_pipeline = pipeline("visual-question-answering")

# Step 4: Load the image and define the question
image = Image.open("elephant.jpeg")  # Ensure this file is uploaded to your Colab environment
question = "Is there an elephant?"

import matplotlib.pyplot as plt
plt.imshow(image)
plt.axis('off')  # Hide the axis
plt.show()

# Step 5: Perform VQA
result = vqa_pipeline(image, question, top_k=1)

# Step 6: Display the result
print(result)

question = "what is this?"
result = vqa_pipeline(image, question, top_k=1)
print(result)

question = "How many elephant are there?"
result = vqa_pipeline(image, question, top_k=1)
print(result)

question = "what is the color of elephants?"
result = vqa_pipeline(image, question, top_k=1)
print(result)

