# -*- coding: utf-8 -*-
"""Image classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pa60fAP7hhIzDGKB9f21X7zIblhUuf-G
"""

# Step 1: Install the necessary libraries
!pip install transformers
!pip install torch torchvision
!pip install pillow

# Step 2: Import the necessary modules
from transformers import pipeline
from PIL import Image
import requests

# Step 3: Create an image classification pipeline
image_classifier = pipeline(task="image-classification")

# Step 4: Define the image you want to classify
# You can use a URL of an image or upload an image to Colab and provide the file path
image_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Kittyply_edit1.jpg/1280px-Kittyply_edit1.jpg"
image = Image.open(requests.get(image_url, stream=True).raw)

# Step 5: Perform image classification
results = image_classifier(image)

# Step 6: Display the classification results
for result in results:
    print(f"Label: {result['label']}, Score: {result['score']:.2f}")

