# -*- coding: utf-8 -*-
"""Text generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxUjV84EtOa-ryeYVLDzoGK4afZMU_2O
"""

# Step 1: Install the necessary library
!pip install transformers

# Step 2: Import the necessary modules
from transformers import pipeline

# Step 3: Create a text generation pipeline
text_generator = pipeline(task="text-generation", model="gpt2")

# Step 4: Define the prompt for text generation
prompt = "Once upon a time in a land far, far away"

# Step 5: Generate text based on the prompt
generated_texts = text_generator(prompt, max_length=50, num_return_sequences=1)

# Step 6: Display the generated text
for idx, generated_text in enumerate(generated_texts):
    print(f"Generated Text {idx + 1}: {generated_text['generated_text']}\n")

