# -*- coding: utf-8 -*-
"""Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mk89__NtUJeHhtgAsSahhC1eroJQMTw0
"""

# Step 1: Install the necessary library
!pip install transformers

# Step 2: Import the necessary modules
from transformers import pipeline

# Step 3: Create a summarization pipeline
summarizer = pipeline(task="summarization")

# Step 4: Define the text you want to summarize
text = """
In a recent development, the scientific community has made significant strides in the field of renewable energy.
Researchers have developed a new solar panel technology that promises to increase efficiency by 20% compared to existing models.
This breakthrough could lead to more affordable and widespread adoption of solar energy, contributing to global efforts to reduce carbon emissions and combat climate change.
The new technology utilizes advanced materials and innovative design to capture sunlight more effectively and convert it into electricity.
This marks a major step forward in the pursuit of sustainable energy solutions.
"""

# Step 5: Generate a summary of the text
summary = summarizer(text, max_length=50, min_length=25, do_sample=False)

# Step 6: Display the summary
print("Summary:")
print(summary[0]['summary_text'])

