# -*- coding: utf-8 -*-
"""GTTS Text to Sound.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y56bXwJK7XA7pSyY2_WWCCwEJWcdIUAf
"""

!pip install gTTS

!pip install playsound

from gtts import gTTS
from playsound import playsound

text = "Welcome to the AI and Machine Learning Playground, where innovation meets creativity."
var = gTTS(text=text, lang='en', slow=False )
var.save("audio.mp3")


