# -*- coding: utf-8 -*-
"""Document question answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdEnOkGqYtfAr79t7cFoCAnHL-4ChiC8
"""

# Step 1: Install the necessary libraries
!pip install PyPDF2
!pip install transformers
!pip install torch

# Step 2: Import the necessary modules
import PyPDF2
from transformers import pipeline# Step 4: Extract text from the PDF
pdf_path = "About_India.pdf"  # Ensure this file is uploaded to your Colab environment
document_text = extract_text_from_pdf(pdf_path)

# Step 3: Define a function to extract text from a PDF
def extract_text_from_pdf(pdf_path):
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        text = ""
        for page in reader.pages:
            text += page.extract_text()
    return text

# Step 4: Extract text from the PDF
pdf_path = "document.pdf"  # Ensure this file is uploaded to your Colab environment
document_text = extract_text_from_pdf(pdf_path)

# Step 5: Set up the question-answering pipeline
qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

# Step 6: Define the question
question = "What is the main topic of the document?"

# Step 7: Perform Question Answering
result = qa_pipeline(question=question, context=document_text)

print("Question:", question)
print("Answer:", result['answer'])

question = "How many states are there in India?"
result = qa_pipeline(question=question, context=document_text)
print("Question:", question)
print("Answer:", result['answer'])

question = "What is famous in Agra?"
result = qa_pipeline(question=question, context=document_text)
print("Question:", question)
print("Answer:", result['answer'])

question = "What are the states in South India?"
result = qa_pipeline(question=question, context=document_text)
print("Question:", question)
print("Answer:", result['answer'])

question = "Which is 'pink city' in India?"
result = qa_pipeline(question=question, context=document_text)
print("Question:", question)
print("Answer:", result['answer'])

