# -*- coding: utf-8 -*-
"""Automatic speech recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y56VVROjxft-4Ge8HGuvDzqHUnId6SnD
"""

# Step 1: Install the necessary libraries
!pip install transformers
!pip install torch torchaudio

# Step 2: Import the necessary modules
from transformers import pipeline

# Step 3: Create an automatic speech recognition pipeline
asr_pipeline = pipeline(task="automatic-speech-recognition", model="facebook/wav2vec2-base-960h")

# Step 4: Define the path to the local audio file
audio_path = "audio.mp3"

# Step 5: Perform speech recognition
transcription = asr_pipeline(audio_path)

# Step 6: Display the transcription result
print("Transcription:")
print(transcription['text'])

